/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tecnologiabasica.jettyapidesktop.view;


import com.tecnologiabasica.jettyapiclient.api.controller.JUserInfoApiController;
import com.tecnologiabasica.jettyapiclient.api.listener.IUserInfoCreateListener;
import com.tecnologiabasica.jettyapiclient.api.listener.IUserInfoUpdateListener;
import com.tecnologiabasica.jettyapicommons.entity.JUserInfoEntity;

/**
 *
 * @author afonso
 */
public class JNewDialog extends javax.swing.JDialog {

    private JUserInfoEntity entity = null;

    /**
     * Creates new form JNewDialog
     */
    public JNewDialog(java.awt.Frame parent, boolean modal, JUserInfoEntity entity) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        this.entity = entity;
        if (entity == null) {
            setTitle("Novo Usuário");
        } else {
            setTitle("Alterar Usuário");
            tfName.setText(entity.getUserName());
            tfPassword.setText(entity.getUserPassword());
            tfEmail.setText(entity.getEmail());
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbName.setText("Nome:");

        lbPassword.setText("Senha:");

        lbEmail.setText("Email:");

        btSave.setText("Salvar");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        lbStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbName)
                                    .addComponent(lbPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btSave)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPassword)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        if (entity == null) {
            entity = new JUserInfoEntity();
            entity.setUserName(tfName.getText());
            entity.setUserPassword(tfPassword.getText());
            entity.setEmail(tfEmail.getText());
            JUserInfoApiController apiController = new JUserInfoApiController();
            apiController.create(entity, new UserInfoCreateListener());
        } else {
            entity.setUserName(tfName.getText());
            entity.setUserPassword(tfPassword.getText());
            entity.setEmail(tfEmail.getText());
            JUserInfoApiController apiController = new JUserInfoApiController();
            apiController.update(entity, new UserInfoUpdateListener());            
        }
    }//GEN-LAST:event_btSaveActionPerformed

    public JUserInfoEntity getEntity() {
        return entity;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSave;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPassword;
    // End of variables declaration//GEN-END:variables

    private class UserInfoCreateListener implements IUserInfoCreateListener {

        @Override
        public void onSucess(JUserInfoEntity entity) {
            dispose();
        }

        @Override
        public void onEmailNotValid() {
            tfEmail.setText("");
            tfEmail.requestFocus();
            lbStatus.setText("Email informado não é válido!"); 
            entity = null;
        }

        @Override
        public void onEmailInUse() {
            tfEmail.setText("");
            tfEmail.requestFocus();
            lbStatus.setText("Email informado já está em uso!");
            entity = null;
        }

        @Override
        public void onError() {
            lbStatus.setText("Erro ao salvar usuário no servidor!");
            entity = null;
        }

        @Override
        public void onUnknow() {
            lbStatus.setText("Erro desconhecido!");
            entity = null;

        }

        @Override
        public void onFailure(String message) {
            lbStatus.setText("Falha ao salvar dados: " + message);
            entity = null;
        }
    }
    
    private class UserInfoUpdateListener implements IUserInfoUpdateListener {

        @Override
        public void onSucess(JUserInfoEntity entity) {
            dispose();
        }

        @Override
        public void onError() {
             lbStatus.setText("Erro ao salvar usuário no servidor!");
        }

        @Override
        public void onUnknow() {
            lbStatus.setText("Erro desconhecido!");
        }

        @Override
        public void onFailure(String message) {
            lbStatus.setText("Falha ao salvar dados: " + message);
        }
        
    }
}
